name: Deploy on Server

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v3

    # Adicione este passo para mudar a pasta de trabalho para "vendas"
    - name: Change Working Directory to 'vendas'
      run: cd vendas

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file ./pom.xml  # Especifique o caminho correto para o pom.xml

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: "gustavoantony"
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: gustavoantony/vendaapi:${{ github.sha }}
        
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_TEST }}
        username: "ec2-user"
        key: ${{ secrets.KEY_TEST }}
        port: 22
        script: |
          docker stop vendaapi
          docker rm --force vendaapi
          docker run  -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} -d -p 8080:8080 --name vendaapi gustavoantony/vendaapi:${{ github.sha }}
